### ISSUE TITLE
Creating API for Database 

### ISSUE THREAD

**Issue by NickP123** [superhealthyminds/healthyminds#12]
- [ ] Setup API for posts
- [ ] Setup API for comments
- [ ] Setup API for users
- [ ] Setup API for messages
- [ ] Setup API for diseases
- [ ] Setup API for chatrooms
- [ ] Setup API for tags

- [ ] Spike in VUE study time to ensure we are ready to code in the front-end. Our original expectations were to move forward with some aspects of the front-end today, but there is a requirement for a further day of project based study that shows the use of both VUE and Express in an example project.

**Comment by idantb101** [comment]
good issue: +1:

**Comment by Amirk390** [comment]
I'll work on the API for users

**Comment by NickP123** [comment]
I'm going to work on the API for comments

**Comment by harrygfox** [comment]
Does the time estimation need to change on this one, @superhealthyminds/developers?

**Comment by NickP123** [comment]
API for comments. At present the comments table has nothing it can use to link to a post. Post however can link to a commentId. I believe we have this the wrong way around. For example, at present their is no way to search for all comments that have been written in relation to a particular post. We need to update the Database so that we can then made the correct API calls

**Comment by idantb101** [comment]
Working on tags

**Comment by Amirk390** [comment]
i'll work on the diseases API

**Comment by Amirk390** [comment]
Doing the messages 

> Setup API for messages (messages in the chat)

**Comment by harrygfox** [comment]
@superhealthyminds/developers please confirm that this is working, and then CLOSE!
